[translation]
# Назва файлу з текстом
input_file = Steve_Jobs_text.txt

# Назва або код мови, на яку необхідно перекласти текст
dest_language = en

# Назва модуля пакету, який буде використаний при перекладі
# Можливі значення: gtrans4_module, gtrans3_module, deeptr_module
module = deeptr_module

# Куди вивести результат: screen або file
output = screen

# Кількість речень, які треба прочитати із заданого файлу і перекласти
sentences_count = 3
